// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enyemnkkqmnxkbjttqlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVueWVtbmtrcW1ueGtianR0cWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjAyOTUsImV4cCI6MjA2NTU5NjI5NX0.JnXV7NUZEnTIZFX_XxCkyAJ-Pfs08FB0QiblLUUGRQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);